version: "3"
services:
  quizantdb:
    image: postgres:latest
    container_name: QUIZANT_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
  # APP*****************************************
  quizantapp:
    image: gebert/quizant:latest
    container_name: QUIZANT_APP
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    links:
      - quizantdb:quizantdb
volumes:
  postgres-data: