CREATE SCHEMA IF NOT EXISTS QUIZ;
CREATE SEQUENCE QUIZ.PK_SEQ_QUIZ START WITH 1;
CREATE SEQUENCE QUIZ.PK_SEQ_USER START WITH 1;
CREATE SEQUENCE QUIZ.PK_SEQ_ANSWER START WITH 1;
CREATE SEQUENCE QUIZ.PK_SEQ_ATTEMPT START WITH 1;
CREATE SEQUENCE QUIZ.PK_SEQ_QUESTION START WITH 1;

CREATE TABLE QUIZ.ANSWER
(
    ID          INTEGER NOT NULL DEFAULT nextval('QUIZ.PK_SEQ_ANSWER'),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    VERSION     INTEGER,
    ANSWER_TEXT VARCHAR(255),
    POINTS      NUMERIC NOT NULL,
    ID_QUESTION BIGINT
);
ALTER TABLE QUIZ.ANSWER
    ADD CONSTRAINT PK_ANSWER PRIMARY KEY (ID);

CREATE TABLE QUIZ.ATTEMPT
(
    ID          INTEGER NOT NULL DEFAULT nextval('QUIZ.PK_SEQ_ATTEMPT'),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    VERSION     INTEGER,
    USERNAME    VARCHAR(255),
    ID_QUIZ     BIGINT
);

ALTER TABLE QUIZ.ATTEMPT
    ADD CONSTRAINT PK_ATTEMPT PRIMARY KEY (ID);

CREATE TABLE QUIZ.QUESTION
(
    ID            INTEGER NOT NULL DEFAULT nextval('QUIZ.PK_SEQ_QUESTION'),
    CREATE_DATE   TIMESTAMP,
    UPDATE_DATE   TIMESTAMP,
    VERSION       INTEGER,
    QUESTION_TEXT VARCHAR(255),
    ID_QUIZ       BIGINT
);
ALTER TABLE QUIZ.QUESTION
    ADD CONSTRAINT PK_QUESTION PRIMARY KEY (ID);

CREATE TABLE QUIZ.QUIZ
(
    ID          INTEGER NOT NULL DEFAULT nextval('QUIZ.PK_SEQ_QUIZ'),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    VERSION     INTEGER,
    NAME        VARCHAR(255),
    ID_OWNER    BIGINT
);
ALTER TABLE QUIZ.QUIZ
    ADD CONSTRAINT PK_QUIZ PRIMARY KEY (ID);

CREATE TABLE QUIZ.USER
(
    ID          INTEGER NOT NULL DEFAULT nextval('QUIZ.PK_SEQ_USER'),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    VERSION     INTEGER,
    LOGIN       VARCHAR(255),
    PASSWORD    VARCHAR(255)
);
ALTER TABLE QUIZ.USER
    ADD CONSTRAINT PK_USER PRIMARY KEY (ID);

ALTER TABLE QUIZ.ANSWER
    ADD CONSTRAINT FK_ANSWER_QUESTION_ID FOREIGN KEY (ID_QUESTION) REFERENCES QUIZ.QUESTION (ID);
ALTER TABLE QUIZ.QUESTION
    ADD CONSTRAINT FK_QUESTION_QUIZ_ID FOREIGN KEY (ID_QUIZ) REFERENCES QUIZ.QUIZ (ID);
ALTER TABLE QUIZ.ATTEMPT
    ADD CONSTRAINT FK_ATTEMPT_QUIZ_ID FOREIGN KEY (ID_QUIZ) REFERENCES QUIZ.QUIZ (ID);
ALTER TABLE QUIZ.QUIZ
    ADD CONSTRAINT FK_QUIZ_USER_ID FOREIGN KEY (ID_OWNER) REFERENCES QUIZ.USER (ID);